include(":app")
include(":features:inbox")
include(":features:permissions")
include(":repository:message")
include(":components:service")
include(":components:receiver")
include(":components:notification")
